#!/bin/bash
#
# Simple script to readd my packages to cblrepo.db
#

pkgs="smallcheck,1.1.1
      lazysmallcheck,0.6
      logict,0.6.0.2
      hood,0.2
      tasty-smallcheck,0.8
      quickspec,0.9.5
      spoon,0.3.1
      tagshare,0.0
      testing-feat,0.4.0.2"
pkgnames="smallcheck
          lazysmallcheck
    	  logict
    	  hood
          tasty-smallcheck
          quickspec
          spoon
          tagshare
          testing-feat"

echo "Avaliable versions:"
for pkg in $pkgnames; do cblrepo versions $pkg; done
echo -n "Adding versions:"
for pkg in $pkgs; do echo -n " $pkg"; done
echo
cblrepo add $pkgs
echo
echo "You may need to do some bumping."
echo "If you haven't had to uninstall them, bump to the latest value"
echo "If you had to uninstall them or unsure, bump to one more"
echo
echo To bump: cblrepo bump --inclusive $pkgnames
echo
echo "As of 2014-07-28, I'm on 7 on all packages (6 bumps)."
echo
echo "Afterwards, please remember to use the current ghc"
echo cblrepo pkgbuild --ghc-version 7.8.3 --ghc-release 1 $pkgnames

