#!/bin/bash
#
# Simple script to readd my packages to cblrepo.db
#

mypackages=(
	smallcheck,1.1.1
    lazysmallcheck,0.6
	logict,0.6.0.2
)
pkgs=${mypackages[@]}

echo "Avaliable versions:"
cblrepo versions logict
cblrepo versions smallcheck
cblrepo versions lazysmallcheck
echo "Adding versions: $pkgs"
cblrepo add $pkgs
echo
echo "You may need to do some bumping."
echo "If you haven't had to uninstall them, bump to the latest value"
echo "If you had to uninstall them or unsure, bump to one more"
echo
echo To bump: cblrepo bump --inclusive $pkgs

