#!/bin/bash
#
# Simple script to readd my packages to cblrepo.db
#

pkgs="smallcheck,1.1.1
      lazysmallcheck,0.6
      logict,0.6.0.2
      hood,0.2"
pkgnames="smallcheck
          lazysmallcheck
		  logict
		  hood"

echo "Avaliable versions:"
cblrepo versions logict
cblrepo versions smallcheck
cblrepo versions lazysmallcheck
echo -n "Adding versions:"
for pkg in $pkgs; do echo -n " $pkg"; done
echo
cblrepo add $pkgs
echo
echo "You may need to do some bumping."
echo "If you haven't had to uninstall them, bump to the latest value"
echo "If you had to uninstall them or unsure, bump to one more"
echo
echo To bump: cblrepo bump --inclusive $pkgnames
echo
echo "Afterwards, please remember to use the current ghc"
echo cblrepo pkgbuild --ghc-version 7.8.2 --ghc-release 1 $pkgnames

